/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tercerexamenpdi;

import javax.swing.JDesktopPane;

/**
 *
 * @author Fer
 */
public class Main2Form extends javax.swing.JPanel {

    /**
     * Creates new form Main2Form
     */
    public Main2Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pane1 = new javax.swing.JDesktopPane();

        javax.swing.GroupLayout Pane1Layout = new javax.swing.GroupLayout(Pane1);
        Pane1.setLayout(Pane1Layout);
        Pane1Layout.setHorizontalGroup(
            Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        Pane1Layout.setVerticalGroup(
            Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane1)
        );
    }// </editor-fold>//GEN-END:initComponents
    public JDesktopPane getInnerPanel() {
        return Pane1;
    }

    public void setInnerPanel(JDesktopPane InnerPanel) {
        this.Pane1 = Pane1;
    }

    protected void resetInnerPanel(){
        Pane1.removeAll();
    }
    
    protected int Width(){
        return Pane1.getWidth();
    }
    
    protected int Height(){
        return Pane1.getHeight();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Pane1;
    // End of variables declaration//GEN-END:variables
}
