/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tercerexamenpdi.Punto_4;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Fer
 */
public class Punto_4_MainPanel extends javax.swing.JPanel {

    public boolean respuesta = true;
    public boolean Eimagen1 = false;
    public boolean Eimagen2 = false;
    public boolean medida = false;
    
    int contador = 0;
    
    //final MessageDialog mes;
        
    //mes = new MessageDialog();
    
    JLabel label, Olabel, Flabel;
    JScrollPane scroll, Oscroll, Fscroll;
    
    BufferedImage imagen = null;
    BufferedImage imagen2 = null;
    BufferedImage imagen3 = null;
    File imagenSeleccionada, imagensel2, imagensel3;
    Color arreglo[][], arregloNoMod[][], arregloFin[][];
    double alfa=0, beta = 0;
    
    /**
     * Creates new form Punto_4_MainPanel
     */
    public Punto_4_MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        texto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Cargar Imagen 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cargar Imagen 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Convertir imagen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Inserte un valor entre 0 y 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(197, 197, 197))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double[] x = new double[256];
                if (medida == true) {
                    JFileChooser Buscar = new JFileChooser();
                    FileNameExtensionFilter extension = new FileNameExtensionFilter("JPG &  BMP & PNG", "jpg", "bmp", "png");
                    Buscar.setFileFilter(extension);
                    int flag = Buscar.showOpenDialog(null);
                    //Comprobamos que pulse en aceptar
                    if (flag == JFileChooser.APPROVE_OPTION) {
                        try {
                            //Devuelve el fichero seleccionado
                            imagenSeleccionada = Buscar.getSelectedFile();
                            //Asignamos a la variable bmp la imagen leida
                            imagen = ImageIO.read(imagenSeleccionada);
                            imagen3 = ImageIO.read(imagenSeleccionada);
                            Eimagen1 = true;
                        } catch (IOException e) {

                        }
                        label.setIcon(new ImageIcon(imagen));
                        //Recorremos la imagen
                        //Se vacían los pixeles a un arreglo de Colores
                        arreglo = new Color[imagen.getHeight()][imagen.getWidth()];
                        for (int i = 0; i < imagen.getHeight(); i++) {
                            for (int j = 0; j < imagen.getWidth(); j++) {
                                arreglo[i][j] = new Color(imagen.getRGB(j, i));
                            }
                        }
                        for (int i = 0; i < 256; i++) {
                            x[i] = (double) i;
                        }
                    }
                } else {
                        medida = true;
                        JFileChooser Buscar = new JFileChooser();
                        FileNameExtensionFilter extension = new FileNameExtensionFilter("JPG &  BMP & PNG", "jpg", "bmp", "png");
                        Buscar.setFileFilter(extension);
                        int flag = Buscar.showOpenDialog(null);
                        //Comprobamos que pulse en aceptar
                        if (flag == JFileChooser.APPROVE_OPTION) {
                            try {
                                //Devuelve el fichero seleccionado
                                imagenSeleccionada = Buscar.getSelectedFile();
                                //Asignamos a la variable bmp la imagen leida
                                imagen = ImageIO.read(imagenSeleccionada);
                                imagen3 = ImageIO.read(imagenSeleccionada);
                                Eimagen1 = true;
                            } catch (IOException e) {

                            }
                            label.setIcon(new ImageIcon(imagen));
                            //Recorremos la imagen
                            //Se vacían los pixeles a un arreglo de Colores
                            arreglo = new Color[imagen.getHeight()][imagen.getWidth()];
                            for (int i = 0; i < imagen.getHeight(); i++) {
                                for (int j = 0; j < imagen.getWidth(); j++) {
                                    arreglo[i][j] = new Color(imagen.getRGB(j, i));
                                }
                            }
                            for (int i = 0; i < 256; i++) {
                                x[i] = (double) i;
                            } 
                        }
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double[] x = new double[256];
                if (contador == 1) {
                    JFileChooser Buscar = new JFileChooser();
                    FileNameExtensionFilter extension = new FileNameExtensionFilter("JPG &  BMP & PNG", "jpg", "bmp", "png");
                    Buscar.setFileFilter(extension);
                    int flag = Buscar.showOpenDialog(null);
                    //Comprobamos que pulse en aceptar
                    if (flag == JFileChooser.APPROVE_OPTION) {
                        try {
                            //Devuelve el fichero seleccionado
                            imagenSeleccionada = Buscar.getSelectedFile();
                            //Asignamos a la variable bmp la imagen leida
                            imagen2 = ImageIO.read(imagenSeleccionada);
                            Eimagen2 = true;
                        } catch (IOException e) {

                        }
                        Flabel.setIcon(new ImageIcon(imagen2));
                        //Recorremos la imagen
                        //Se vacían los pixeles a un arreglo de Colores
                        arregloNoMod = new Color[imagen2.getHeight()][imagen2.getWidth()];
                        for (int i = 0; i < imagen2.getHeight(); i++) {
                            for (int j = 0; j < imagen2.getWidth(); j++) {
                                arregloNoMod[i][j] = new Color(imagen2.getRGB(j, i));
                            }
                        }
                        for (int i = 0; i < 256; i++) {
                            x[i] = (double) i;
                        }
                    }
                } else {
                    contador = 1;
                    JFileChooser Buscar = new JFileChooser();
                    FileNameExtensionFilter extension = new FileNameExtensionFilter("JPG &  BMP & PNG", "jpg", "bmp", "png");
                    Buscar.setFileFilter(extension);
                    int flag = Buscar.showOpenDialog(null);
                    //Comprobamos que pulse en aceptar
                    if (flag == JFileChooser.APPROVE_OPTION) {
                        try {
                            //Devuelve el fichero seleccionado
                            imagenSeleccionada = Buscar.getSelectedFile();
                            //Asignamos a la variable bmp la imagen leida
                            imagen2 = ImageIO.read(imagenSeleccionada);
                            Eimagen2 = true;
                        } catch (IOException e) {

                        }
                        Flabel.setIcon(new ImageIcon(imagen2));
                        //Recorremos la imagen
                        //Se vacían los pixeles a un arreglo de Colores
                        arregloNoMod = new Color[imagen2.getHeight()][imagen2.getWidth()];
                        for (int i = 0; i < imagen2.getHeight(); i++) {
                            for (int j = 0; j < imagen2.getWidth(); j++) {
                                arregloNoMod[i][j] = new Color(imagen2.getRGB(j, i));
                            }
                        }
                        for (int i = 0; i < 256; i++) {
                            x[i] = (double) i;
                        }
                    }
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int Rojo1, Rojo2, azul1, azul2, verde1, verde2;
        double Rojofin, verdefin, azulfin;
        double rojo1a, verde1a, azul1a;
        double rojo2b, azul2b, verde2b;
        if(Eimagen1==false){
            JOptionPane.showMessageDialog(null, "Error: No ha seleccionado la 'Imagen 1'", "Error!", JOptionPane.ERROR_MESSAGE);
        }else{
            if(Eimagen2==false){
                JOptionPane.showMessageDialog(null, "Error: No ha seleccionado la 'Imagen 2'", "Error!", JOptionPane.ERROR_MESSAGE);
            }else{
                if(Eimagen1==true&&Eimagen2==true){
                    if(texto.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Error: No ha ingresado ningún valor", "Error!", JOptionPane.ERROR_MESSAGE);
                    }else{
                        try{
                            Double.parseDouble(texto.getText());
                            respuesta=true;
                        }catch(NumberFormatException ex){
                            respuesta=false;
                        }
                        if(respuesta==false){
                            //mes.Message("Error: Caracteres no numericos", "Error!");
                            JOptionPane.showMessageDialog(null, "Error: Ingresó un valor no númerico", "Error!", JOptionPane.ERROR_MESSAGE);
                        }
                        else{
                            if(Double.parseDouble(texto.getText())<0){
                                //mes.Message("De un numero entre 0 y 255", "Error!");
                                JOptionPane.showMessageDialog(null, "Error: Ingresó un valor menor a 0 (CERO)", "Error!", JOptionPane.ERROR_MESSAGE);
                            }
                            else{
                                if(Double.parseDouble(texto.getText())>1){
                                   JOptionPane.showMessageDialog(null, "Error: Ingresó un valor mayor a 1 (UNO)", "Error!", JOptionPane.ERROR_MESSAGE); 
                                }
                                else{
                                    arregloFin = new Color[imagen.getHeight()][imagen.getWidth()];
                                    System.out.println(texto.getText());
                                    alfa=0;
                                    alfa=Double.parseDouble(texto.getText());
                                    beta=1-alfa;
                                    for (int i = 0; i < imagen.getHeight(); i++) {
                                        for (int j = 0; j < imagen.getWidth(); j++) {
                                            Rojo1 = arreglo[i][j].getRed();
                                            rojo1a = alfa*Rojo1;
                                            Rojo2 = arregloNoMod[i][j].getRed();
                                            rojo2b = beta*Rojo2;
                                            Rojofin = rojo1a+rojo2b;
                                            azul1 = arreglo[i][j].getBlue();
                                            azul1a = alfa*azul1;
                                            azul2 = arregloNoMod[i][j].getBlue();
                                            azul2b = beta*azul2;
                                            azulfin = azul1a+azul2b;
                                            verde1 = arreglo[i][j].getGreen();
                                            verde1a = alfa*verde1;
                                            verde2 = arregloNoMod[i][j].getGreen();
                                            verde2b = beta*verde2;
                                            verdefin = verde1a+verde2b;
                                            Color col = new Color((int) Rojofin, (int) verdefin, (int) azulfin);
                                            int rgb = col.getRGB();
                                            imagen3.setRGB(j, i, rgb);
                                        }
                                    }
                                    Olabel.setIcon(new ImageIcon(imagen3));
                                }
                            }
                        }
                    }
                }
                else{
                    if(Eimagen1==false||Eimagen2==false){
                        JOptionPane.showMessageDialog(null, "Error: Tiene que cargar ambas imagenes", "Error!", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void Todo (){
        //Imagen original
        label = new JLabel();
        label.setBounds(30, 30, 406, 231);
        
        scroll = new JScrollPane();
        scroll.setBounds(30, 30, 406, 231);
        scroll.setViewportView(label);
        this.add(scroll);
        
        //Blanco negro
        
        Olabel = new JLabel();
        Olabel.setBounds(620, 175, 406, 231);
        
        Oscroll = new JScrollPane();
        Oscroll.setBounds(620, 175, 406, 231);
        Oscroll.setViewportView(Olabel);
        this.add(Oscroll);
        
        //Bordes
        
        Flabel = new JLabel();
        Flabel.setBounds(30, 335, 406, 231);
        
        Fscroll = new JScrollPane();
        Fscroll.setBounds(30, 335, 406, 231);
        Fscroll.setViewportView(Flabel);
        this.add(Fscroll);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
